//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal_VNND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assurances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assurances()
        {
            this.Liste_Assurances = new HashSet<Liste_Assurances>();
        }
    
        public int id_assurance { get; set; }
        public string libelle { get; set; }
        //presentation décimal du prix en pourcentage
        public double prix { get; set; }
        public string descriptif { get; set; }
        // prix de l'assurrance en % du prix total presenté en %
        public string prix100 { get { return ((int)Math.Round(prix * 100)).ToString(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liste_Assurances> Liste_Assurances { get; set; }
    }
}
