//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal_VNND.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoVoyage_VNNDEntities : DbContext
    {
        public BoVoyage_VNNDEntities()
            : base("name=BoVoyage_VNNDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agences> Agences { get; set; }
        public virtual DbSet<Assurances> Assurances { get; set; }
        public virtual DbSet<Civilites> Civilites { get; set; }
        public virtual DbSet<Continents> Continents { get; set; }
        public virtual DbSet<Destinations> Destinations { get; set; }
        public virtual DbSet<Dossiers> Dossiers { get; set; }
        public virtual DbSet<Etats_Dossiers> Etats_Dossiers { get; set; }
        public virtual DbSet<OuisNons> OuisNons { get; set; }
        public virtual DbSet<Personnes> Personnes { get; set; }
        public virtual DbSet<Raisons_Annulations> Raisons_Annulations { get; set; }
        public virtual DbSet<Statuts> Statuts { get; set; }
        public virtual DbSet<Voyages> Voyages { get; set; }
        public virtual DbSet<Authentifications> Authentifications { get; set; }
    }
}
